In [1]:
# To work with Excel and CSV files in Python, we need to import the pandas library, which provides powerful data manipulation and analysis tools. If you haven't installed pandas yet, you can do so using pip:
# pip install pandas

import pandas as pd

In [4]:
# Loading an Excel file into a DataFrame

df = pd.read_excel('Test.xlsx')   # In this case, the file is in the same directory as the script. If it's in a different location, provide the full path.

# Loading a CSV file into a DataFrame

# df = pd.read_csv('path/to/your/file.csv')
# df = pd.read_csv(r'path\to\your\file.csv') # The prefix r before the string indicates a raw string, which prevents errors with backslashes (\).

In [2]:
# Loading an Excel file into a DataFrame (using the file path)

df = pd.read_excel('C:/Users/ander/OneDrive/Anderson/Estudo/Python/Importando e salvando arquivo no Python/Test.xlsx')   # Use forward slashes (/) in the file path to avoid issues with backslashes (\) in Windows file paths.

In [3]:
# Loading an Excel file into a DataFrame (using a raw string for the file path)

df = pd.read_excel(r'C:\Users\ander\OneDrive\Anderson\Estudo\Python\Importando e salvando arquivo no Python\Test.xlsx')   # The prefix r before the string indicates a raw string, which prevents errors with backslashes (\).

In [5]:
# Display the column names of the DataFrame

print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [6]:
# View the data in the DataFrame

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047,United Kingdom

In [7]:
# Get the total number of data points in the DataFrame (number of rows multiplied by number of columns)

df.size

88

In [8]:
# Get the number of rows and columns in the DataFrame

df.shape

(11, 8)

In [9]:
# Get information about the DataFrame, including the number of non-null entries, data types of each column, and memory usage

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    11 non-null     int64
 1   StockCode    11 non-null     object
 2   Description  11 non-null     object
 3   Quantity     11 non-null     int64
 4   InvoiceDate  11 non-null     datetime64[ns]
 5   UnitPrice    11 non-null     float64
 6   CustomerID   11 non-null     int64
 7   Country      11 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 836.0+ bytes

In [10]:
# Display the first few rows of the DataFrame to get an overview of the data

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [11]:
# Display the last few rows of the DataFrame to see the most recent entries

df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047,United Kingdom

In [12]:
# Get summary statistics for the numerical columns in the DataFrame, including count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum values.

df.describe()

,InvoiceNo,Quantity,InvoiceDate,UnitPrice,CustomerID
count,11.000000,11.000000,11,11.000000,11.000000
mean,536365.545455,8.181818,2010-12-01 08:27:49.090909184,3.169091,16976.727273
min,536365.000000,2.000000,2010-12-01 08:26:00,1.690000,13047.000000
25%,536365.000000,6.000000,2010-12-01 08:26:00,1.975000,17850.000000
50%,536365.000000,6.000000,2010-12-01 08:26:00,2.750000,17850.000000
75%,536366.000000,6.000000,2010-12-01 08:28:00,3.390000,17850.000000
max,536367.000000,32.000000,2010-12-01 08:34:00,7.650000,17850.000000
std,0.820200,8.022695,NaN,1.695963,1942.909164

In [13]:
# Check for duplicate rows in the DataFrame and count the number of duplicates. The duplicated() method returns a boolean Series indicating whether each row is a duplicate of a previous row, and sum() counts the total number of True values (duplicates).

print("Number of duplicates:", df.duplicated().sum())

Number of duplicates: 0

In [15]:
# Check for missing values in the DataFrame and count the number of missing values in each column. The isnull() method returns a DataFrame of the same shape with boolean values indicating whether each entry is null (missing), and sum() counts the total number of True values (missing) in each column.

df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64